/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Customer' : null } |
  { 'Rider' : null };
export interface Location {
  'id' : bigint,
  'latitude' : number,
  'owner' : Principal,
  'confidenceScore' : bigint,
  'longitude' : number,
  'locationLabel' : string,
  'landmarkNotes' : string,
  'orientation' : string,
}
export type Time = bigint;
export interface UserProfile { 'appRole' : [] | [AppRole], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Verification {
  'id' : bigint,
  'status' : string,
  'locationId' : bigint,
  'timestamp' : Time,
  'rider' : Principal,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignAppRole' : ActorMethod<[Principal, AppRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLocationToRider' : ActorMethod<[bigint, Principal], undefined>,
  'confirmPickup' : ActorMethod<[bigint, string], bigint>,
  'deleteLocation' : ActorMethod<[bigint], undefined>,
  'getAllLocations' : ActorMethod<[], Array<Location>>,
  'getAllVerifications' : ActorMethod<[], Array<Verification>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLocation' : ActorMethod<[bigint], Location>,
  'getLocationAssignments' : ActorMethod<[], Array<[bigint, Principal]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listLocations' : ActorMethod<[], Array<Location>>,
  'listVerifications' : ActorMethod<[], Array<Verification>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLocation' : ActorMethod<
    [string, number, number, string, string, bigint],
    bigint
  >,
  'updateLocation' : ActorMethod<
    [bigint, string, number, number, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];