/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppRole = IDL.Variant({
  'Customer' : IDL.Null,
  'Rider' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'owner' : IDL.Principal,
  'confidenceScore' : IDL.Nat,
  'longitude' : IDL.Float64,
  'locationLabel' : IDL.Text,
  'landmarkNotes' : IDL.Text,
  'orientation' : IDL.Text,
});
export const Time = IDL.Int;
export const Verification = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'locationId' : IDL.Nat,
  'timestamp' : Time,
  'rider' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'appRole' : IDL.Opt(AppRole),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLocationToRider' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'confirmPickup' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'deleteLocation' : IDL.Func([IDL.Nat], [], []),
  'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getAllVerifications' : IDL.Func([], [IDL.Vec(Verification)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLocation' : IDL.Func([IDL.Nat], [Location], ['query']),
  'getLocationAssignments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Principal))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'listVerifications' : IDL.Func([], [IDL.Vec(Verification)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'updateLocation' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppRole = IDL.Variant({ 'Customer' : IDL.Null, 'Rider' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'owner' : IDL.Principal,
    'confidenceScore' : IDL.Nat,
    'longitude' : IDL.Float64,
    'locationLabel' : IDL.Text,
    'landmarkNotes' : IDL.Text,
    'orientation' : IDL.Text,
  });
  const Time = IDL.Int;
  const Verification = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'locationId' : IDL.Nat,
    'timestamp' : Time,
    'rider' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'appRole' : IDL.Opt(AppRole),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLocationToRider' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'confirmPickup' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'deleteLocation' : IDL.Func([IDL.Nat], [], []),
    'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getAllVerifications' : IDL.Func([], [IDL.Vec(Verification)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLocation' : IDL.Func([IDL.Nat], [Location], ['query']),
    'getLocationAssignments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Principal))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'listVerifications' : IDL.Func([], [IDL.Vec(Verification)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'updateLocation' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };